name: geopandas-workshop
channels:
  - conda-forge
dependencies:
  - python
  - jupyterlab>4
  # - geopandas>=1
  - pandas
  - shapely>=2
  - pyogrio
  - pyproj
  - pyarrow
  - mapclassify
  - matplotlib
  - folium
  - contextily
  - geodatasets
  - xyzservices
  - libpysal
  - pip
  - pip:
      - git+https://github.com/geopandas/geopandas.git
